apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-stock-dev
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/Quackusarle/NT114_manifests.git
    targetRevision: HEAD
    path: argocd/apps/mlops-stock
    helm:
      releaseName: mlops-stock
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-stock-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
