apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: mlops-stock-runner
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: Quackusarle/MLOps-Stock
      labels:
        - self-hosted
        - k3s
        - mlops
      image: summerwind/actions-runner:latest
      imagePullPolicy: IfNotPresent
      dockerEnabled: false
      env:
        - name: PIP_CACHE_DIR
          value: /tmp/pip-cache
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      volumes:
        - name: pip-cache
          hostPath:
            path: /mnt/k3s-runner-cache/pip
            type: DirectoryOrCreate
        - name: trivy-cache
          hostPath:
            path: /mnt/k3s-runner-cache/trivy
            type: DirectoryOrCreate
        - name: sonar-cache
          hostPath:
            path: /mnt/k3s-runner-cache/sonar
            type: DirectoryOrCreate
      volumeMounts:
        - name: pip-cache
          mountPath: /tmp/pip-cache
        - name: trivy-cache
          mountPath: /tmp/trivy-cache
        - name: sonar-cache
          mountPath: /tmp/sonar-cache

