sonar.projectKey=mlops-stock
sonar.projectName=MLOps-Stock
sonar.python.version=3.11

sonar.sources=src,services

sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=venv/**,tests/**,**/*.md,**/*.txt
