apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensemble-api
  labels:
    app: ensemble-api
    {{- include "mlops-stock.labels" . | nindent 4 }}
spec:
{{- if not .Values.ensembleApi.autoscaling.enabled }}
  replicas: {{ .Values.ensembleApi.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: ensemble-api
  template:
    metadata:
      labels:
        app: ensemble-api
    spec:
      serviceAccountName: {{ include "mlops-stock.serviceAccountName" . }}
      containers:
        - name: ensemble-api
          image: "{{ .Values.ensembleApi.image.repository }}:{{ .Values.ensembleApi.image.tag }}"
          imagePullPolicy: {{ .Values.ensembleApi.image.pullPolicy }}
          env:
            - name: DATA_SERVICE_URL
              value: "http://data-api:8001/fetch/{}"
            - name: TFT_SERVICE_URL
              value: "http://tft-api:8002/predict/tft"
            - name: LGBM_SERVICE_URL
              value: "http://lgbm-api:8003/predict/lgbm"
            - name: MLFLOW_TRACKING_URI
              value: {{ .Values.mlflow.trackingUri | quote }}

            - name: REDIS_HOST
              value: {{ .Values.ensembleApi.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.ensembleApi.redis.port | quote }}

          ports:
            - name: http
              containerPort: {{ .Values.ensembleApi.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.ensembleApi.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ensemble-api
  labels:
    app: ensemble-api
    {{- include "mlops-stock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ensembleApi.service.type }}
  ports:
    - port: {{ .Values.ensembleApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ensemble-api
